version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: servicehub-postgres

    environment:
      POSTGRES_DB: servicehub_db
      POSTGRES_USER: servicehub
      POSTGRES_PASSWORD: servicehub123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: