version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: servicehub-postgres

    environment:
      POSTGRES_DB: servicehub_db
      POSTGRES_USER: servicehub
      POSTGRES_PASSWORD: servicehub123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: servicehub-redis
    ports:
      - "6379:6379"


volumes:
  postgres_data: